### ISSUE TITLE
Feint yet visible blue lines where pieces of Monika's sprite connects

### ISSUE THREAD

**Issue by WR3nCHe5** [edave64/Doki-Doki-Dialog-Generator#42]
![image](https://github.com/edave64/Doki-Doki-Dialog-Generator/assets/158311667/3adedaeb-209b-4d2b-9a55-08e809b5e516)
![image](https://github.com/edave64/Doki-Doki-Dialog-Generator/assets/158311667/f3e3327a-5d21-4c73-9c87-1656824d3fc6)

**Comment by edave64** [comment]
Thank you for your report.
That is a known issue with the compression of the low-quality preview images. They are also visible for all other characters, it's just particularly noticeable on Monika.
In the latest version, an issue seems to have snuck in that makes the export also use low-quality preview images, instead of using downloading the high-quality images like they are supposed to. Disabling the "Low-quality preview" setting also seems to no longer function.

As a workaround in the mean time, the image export in the panels tool still seems to function as it should.

**Comment by edave64** [comment]
Fix is online, the lines seem to no longer be in the export, and disappear if "Low-quality preview" is disabled.

**Comment by WR3nCHe5** [comment]
awesome, thank you!
